name: Hello DevOps CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Echo Hello World
      run: echo "✅ Code successfully pushed!"
