name: Say Hello on Push

on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Say hello
        run: echo "👋 Hello from your first GitHub Action!"
